### ISSUE TITLE
Websocket connection refused

### ISSUE THREAD

**Issue by murwa** [andromisa/larachet#1]
@admsa i'm new to this stuff and maybe there's something i'm missing; but this line 

``` javascript
var ws = new Larachet('ws://localhost:8080')
```

gives me this in the browser

> WebSocket connection to 'ws://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by murwa** [comment]
as i said, i was new to this; didn't know about 

> php artisan larachet:serve

mind documenting this?

**Comment by shellus** [comment]
谢谢
